name: Build and Test
on: [push, pull_request, workflow_dispatch]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      options: --user root

    env:
      # for firefox
      HOME: /root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: APP_ENV=development yarn run build

      - name: Run tests
        run: yarn run test-full

      - name: Run lint
        run: yarn run lint

      - name: Publish to NPM
        run: |
          # https://www.npmjs.com/settings/dbp-deploy/tokens
          # NPM_TOKEN needs to be a "Publish" token with 2FA disabled!
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
          yarn install
          yarn run build
          # yarn always reports "https://registry.yarnpkg.com/@dbp-topics%2fsignature - Not found", so we are using npm directly
          npm run do-publish
