name: Build and Test
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ci:latest
      options: --user root

    env:
      # for firefox
      HOME: /root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: APP_ENV=development yarn run build

      - name: Run tests
        run: yarn run test-full

      - name: Run lint
        run: yarn run lint
